#ifndef CONF_H_
#define CONF_H_

#include <stdio.h>


#define CONFIG_NRF_RPC 1
#define CONFIG_NRF_RPC_CBOR 1
//#define CONFIG_NRF_RPC_TR_RPMSG 0
#define CONFIG_NRF_RPC_TR_CUSTOM 1
#define CONFIG_NRF_RPC_TR_CUSTOM_INCLUDE "nrf_rpc_shmem.h"
#define CONFIG_NRF_RPC_CMD_CTX_POLL_SIZE 8
#define CONFIG_NRF_RPC_THREAD_POOL_SIZE 3

//#define CONFIG_NRF_RPC_SHMEM_NUM_BLOCKS_32 0
#define CONFIG_NRF_RPC_SHMEM_NUM_BLOCKS_64 1

#ifdef MASTER

#define CONFIG_NRF_RPC_SHMEM_IN_SIZE 1024
#define CONFIG_NRF_RPC_SHMEM_OUT_SIZE 2048

#define SIDE "MASTER"
#define IS_MASTER 1
#define IS_SLAVE 0

#else

#define CONFIG_NRF_RPC_SHMEM_OUT_SIZE 1024
#define CONFIG_NRF_RPC_SHMEM_IN_SIZE 2048

#define SIDE "SLAVE "
#define IS_MASTER 0
#define IS_SLAVE 1

#endif

#endif // CONF_H_
